/**
 * Exact Spectora export column titles from the committed fixture.
 * Do not invent aliases or rename these.
 */
export const SOURCE_COLUMNS = [
  "Section Name",
  "Item Name",
  "Comment Name",
  "Comment Text",
  "Comment Type (info, limit, defect)",
  "Category (-1: Low, 0: Med, 1: High)",
  "Multiple Choice Options (comma-separated)",
  "Unit Type Options (numeric answers only, comma-separated)",
  "Recommendation (from list)",
  "Order (w/i item)",
  "Answer Type (boolean, checkbox, date, number, range, text)",
  "Default Value",
  'Default Value 2 (for "range" types)',
  'Default Unit Type (for "number" and "range" types)',
  "Default Location",
  "Default Estimate Min",
  "Default Estimate Max",
  "Locked",
  "Simple Format",
  "Disable Photos",
  "Uses",
  "Default Photo 1",
  "Default Photo 1 Caption",
  "Default Photo 2",
  "Default Photo 2 Caption",
  "Default Photo 3",
  "Default Photo 3 Caption",
  "Default Photo 4",
  "Default Photo 4 Caption",
  "Default Photo 5",
  "Default Photo 5 Caption",
  "Default Photo 6",
  "Default Photo 6 Caption",
  "Default Photo 7",
  "Default Photo 7 Caption",
  "Default Photo 8",
  "Default Photo 8 Caption",
  "Default Photo 9",
  "Default Photo 9 Caption",
  "Default Photo 10",
  "Default Photo 10 Caption",
  "Last Modified",
] as const;

export type SourceColumn = (typeof SOURCE_COLUMNS)[number];

export const REQUIRED_HEADERS: SourceColumn[] = [
  "Section Name",
  "Item Name",
  "Comment Name",
  "Comment Text",
  "Comment Type (info, limit, defect)",
  "Answer Type (boolean, checkbox, date, number, range, text)",
];

export const COL = {
  sectionName: "Section Name",
  itemName: "Item Name",
  commentName: "Comment Name",
  commentText: "Comment Text",
  commentType: "Comment Type (info, limit, defect)",
  category: "Category (-1: Low, 0: Med, 1: High)",
  multipleChoice: "Multiple Choice Options (comma-separated)",
  unitOptions: "Unit Type Options (numeric answers only, comma-separated)",
  recommendation: "Recommendation (from list)",
  order: "Order (w/i item)",
  answerType: "Answer Type (boolean, checkbox, date, number, range, text)",
  defaultValue: "Default Value",
  defaultValue2: 'Default Value 2 (for "range" types)',
  defaultUnitType: 'Default Unit Type (for "number" and "range" types)',
  defaultLocation: "Default Location",
  estimateMin: "Default Estimate Min",
  estimateMax: "Default Estimate Max",
  locked: "Locked",
  simpleFormat: "Simple Format",
  disablePhotos: "Disable Photos",
  uses: "Uses",
  lastModified: "Last Modified",
} as const satisfies Record<string, SourceColumn>;
